### ISSUE TITLE
Issue in PHP 7.2+ 

### ISSUE THREAD

**Issue by UVLabs** [dwgebler/php-encryption#1]
Sodium was included by default in PHP 7.2+ without the need for an extension:

>Developers can use Sodium for PHP encryption and decryption with PHP 7.2 and newer without an extension. If you want to use Sodium with PHP 7.0 or 7.1, you need to install a[ PECL extension](https://pecl.php.net/package/libsodium).

Cited here: https://www.zend.com/blog/libsodium-and-php-encrypt

On this line: https://github.com/dwgebler/php-encryption/blob/master/src/Encryption.php#L14 you're checking for the existence of the extension regardless of PHP version and stopping the script if it doesn't exist.

I had to get around this by commenting out the line since I'm using PHP 8+ and know that the library is included.

**Comment by dwgebler** [comment]
Hi @UVLabs although Sodium extension is _bundled_ with PHP >= 7.2 rather than installed via PECL, it is still an extension. The line `extension_loaded('sodium')` will still return `true` on newer versions (including 8/8.1) and it's still possible to compile PHP without it, so the check is still necessary.
